### PR TITLE
refactor(client): alert and typography-components

### PR DESCRIPTION
**Pull request by lessp**
**Issue:** Closes #
**Intent:**
**How to test (optional):**

### CODE REVIEW

**Comment by faroutchris** [comment]
@lessp Check this pr out when you have time

**Comment by lessp** [comment]
> @lessp Check this pr out when you have time
> 
> Tried to make a test in Book_test.re that would check for the notification. But I can't seem to trigger the necessary state changes. Maybe we should test the notification component separately.

Cool! Will have a look!

I think it makes sense for the Book-test to tell if `dispatchNotification` was ever called, since this in the scope of what the component promises to deliver.

**Comment by momentiris** [comment]
Yeah, it makes sense for the Book-test to tell if dispatchNotification was called, but how is this best implemented? The way I see it now, we first test initial rendering, then rendering with dropdown. Since the notification is triggered by the StartDrone component firing its dispatch, which propagates back up to Book, wouldn't we have to implement all these steps leading to that event in the Book-tests?

Could we also not do that, and instead leave those kind of flows to cypress?

yes? no? i'm a bit unsure

**Comment by lessp** [comment]
Yeah, I agree that leaving the more thorough, and deeper testing to Cypress is fine. We investigated a bit on what it'd take to go all the way, and it's a bit clumsy without top-level await as well. 👍

**Comment by lessp** [comment]
> I say skip unit tests like Book_test.re, and perhaps for most views/pages, and go with cypress tests for that instead!

Hmm, I'll have to disagree here. I like having tests running as I code, and may sometimes do TDD. The Cypress-tests are great but are cumbersome to run while developing. Spending some time writing unit-tests, I feel, does not justify a request for changes. 🙂

**Comment by momentiris** [comment]
> > I say skip unit tests like Book_test.re, and perhaps for most views/pages, and go with cypress tests for that instead!
> 
> Hmm, I'll have to disagree here. I like having tests running as I code, and may sometimes do TDD. The Cypress-tests are great but are cumbersome to run while developing. Spending some time writing unit-tests, I feel, does not justify a request for changes. 🙂

Valid points! I see now that my change request review was pretty poorly expressed. There was some Skipped test and some logs that I was actually thinking about. :) 

About the unit testing, I agree about the perks of having tests running while coding. Nevertheless, I feel that these long unit runs with multiple mocked responses are taking more value than they are giving. Every time we mock, we're kind of moving away from reality and introducing possible overhead work in places we will often want to test e2e too.

**Comment by lessp** [comment]
> > > I say skip unit tests like Book_test.re, and perhaps for most views/pages, and go with cypress tests for that instead!
> > 
> > 
> > Hmm, I'll have to disagree here. I like having tests running as I code, and may sometimes do TDD. The Cypress-tests are great but are cumbersome to run while developing. Spending some time writing unit-tests, I feel, does not justify a request for changes. 🙂
> 
> Valid points! I see now that my change request review was pretty poorly expressed. There was some Skipped test and some logs that I was actually thinking about. :)
> 
> About the unit testing, I agree about the perks of having tests running while coding. Nevertheless, I feel that these long unit runs with multiple mocked responses are taking more value than they are giving. Every time we mock, we're kind of moving away from reality and introducing possible overhead work in places we will often want to test e2e too.

Definitely! We explored how involved it would be to mock multiple responses, but ultimately decided it wasn't worth it! Sometimes it takes once to layout a suite that you then can follow, but this time it felt a bit too much for it to be worth it. 👍

**Comment by faroutchris** [comment]
Is this ready to be merged @lessp

**Comment by lessp** [comment]
> Is this ready to be merged @lessp

Yes, I'd say so!

**Pull request merged**
